---
abstract: 'Generate HTML content from Markdown files'
author:
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Preprocess-Markdown
requires:
  Cwd: 0
  Dancer: 0
  Dancer::Plugin: 0
  File::Spec::Functions: 0
  Text::Markdown: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/odyniec/p5-Dancer-Plugin-Preprocess-Markdown/issues
  homepage: https://github.com/odyniec/p5-Dancer-Plugin-Preprocess-Markdown
  repository: https://github.com/odyniec/p5-Dancer-Plugin-Preprocess-Markdown.git
version: 0.020
